# syntax=docker/dockerfile:1.7
# Generated by setup-fx.sh. The image is always Linux; the host may be
# macOS or Linux. Never pass AI_GATEWAY_API_KEY as a build-arg.

ARG UBUNTU_VERSION=24.04
FROM ubuntu:${UBUNTU_VERSION}

ARG FX_VERSION=
ARG FX_MODEL=zai/glm-5.2
ARG FX_UID=1000
ARG FX_GID=1000
ARG TARGETARCH

LABEL org.opencontainers.image.title="fx-sandbox" \
      org.opencontainers.image.description="Hardened Ubuntu image for Vercel Labs fx" \
      org.opencontainers.image.source="https://github.com/da-beda/fx-sandbox"

ENV DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    FX_DISABLE_KEYCHAIN=1 \
    FX_MODEL=${FX_MODEL} \
    FX_PERMISSION_MODE=auto \
    FX_HOME=/home/fx/.fx \
    HOME=/home/fx \
    PATH=/usr/local/bin:/usr/bin:/bin

RUN groupadd --gid "${FX_GID}" fx \
 && useradd --uid "${FX_UID}" --gid "${FX_GID}" \
      --create-home --home-dir /home/fx \
      --shell /bin/bash \
      --comment "fx sandbox user" fx \
 && mkdir -p /workspace /home/fx/.fx /home/fx/.config \
 && chown -R fx:fx /home/fx /workspace \
 && chmod 0700 /home/fx /home/fx/.fx

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends \
      ca-certificates curl tar gzip git jq \
      python3 python3-pip python3-venv \
      ripgrep fd-find less file patch bash \
      build-essential pkg-config \
 && rm -rf /var/lib/apt/lists/*

# fx is a Linux binary inside the image (linux-x86_64 / linux-aarch64).
RUN set -eu; \
    case "${TARGETARCH:-}" in \
      amd64) arch=x86_64 ;; \
      arm64) arch=aarch64 ;; \
      "") case "$(uname -m)" in x86_64|amd64) arch=x86_64 ;; arm64|aarch64) arch=aarch64 ;; *) echo "arch? $(uname -m)"; exit 1 ;; esac ;; \
      *) echo "unsupported TARGETARCH=${TARGETARCH}"; exit 1 ;; \
    esac; \
    ver="${FX_VERSION}"; \
    if [ -z "$ver" ]; then ver="$(curl -fsSL https://releases.fx.sh/latest.txt | tr -d "[:space:]")"; fi; \
    cd /tmp; \
    curl -fsSL -o fx.tgz "https://releases.fx.sh/${ver}/fx-linux-${arch}.tar.gz"; \
    curl -fsSL -o fx.sha "https://releases.fx.sh/${ver}/fx-linux-${arch}.tar.gz.sha256"; \
    got="$(sha256sum fx.tgz | awk "{print \$1}")"; \
    expect="$(awk "{print \$1}" fx.sha | tr -d "[:space:]")"; \
    [ "$got" = "$expect" ] || { echo "sha256 mismatch $got != $expect"; exit 1; }; \
    tar --no-same-owner -xzf fx.tgz; \
    install -m 0755 /tmp/fx /usr/local/bin/fx; \
    rm -rf /tmp/fx /tmp/fx.tgz /tmp/fx.sha; \
    fx --version

COPY entrypoint.sh /usr/local/bin/fx-entrypoint
COPY config/settings.json /usr/local/share/fx-sandbox/settings.json
COPY config/workspace.fx.json /usr/local/share/fx-sandbox/workspace.fx.json

RUN chmod 0755 /usr/local/bin/fx-entrypoint \
 && install -m 0600 -o fx -g fx /usr/local/share/fx-sandbox/settings.json /home/fx/.fx/settings.json \
 && printf "export FX_DISABLE_KEYCHAIN=1\\nexport FX_MODEL=%s\\n" "${FX_MODEL}" > /etc/profile.d/fx.sh \
 && chmod 0644 /etc/profile.d/fx.sh

USER fx:fx
WORKDIR /workspace
STOPSIGNAL SIGINT
ENTRYPOINT ["/usr/local/bin/fx-entrypoint"]
CMD ["fx"]
