# syntax=docker/dockerfile:1.7
# Generated by setup-fx.sh. The image is always Linux; the host may be
# macOS or Linux. Never pass AI_GATEWAY_API_KEY as a build-arg.

ARG UBUNTU_VERSION=24.04
FROM ubuntu:${UBUNTU_VERSION}

ARG FX_VERSION=
ARG FX_MODEL=zai/glm-5.2
ARG FX_UID=1000
ARG FX_GID=1000
ARG TARGETARCH
# Optional apt mirror, e.g. http://de.ports.ubuntu.com/ubuntu-ports
ARG APT_MIRROR=

LABEL org.opencontainers.image.title="fx-sandbox" \
      org.opencontainers.image.description="Hardened Ubuntu image for Vercel Labs fx" \
      org.opencontainers.image.source="https://github.com/da-beda/fx-sandbox"

ENV DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    FX_DISABLE_KEYCHAIN=1 \
    FX_MODEL=${FX_MODEL} \
    FX_PERMISSION_MODE=auto \
    FX_HOME=/home/fx/.fx \
    HOME=/home/fx \
    PATH=/usr/local/bin:/usr/sbin:/usr/bin:/bin

# Slim package set (no compiler toolchain). Retries + optional mirror
# because Docker Desktop on macOS often flakes on ports.ubuntu.com:80.
RUN set -eu; \
    printf 'Acquire::Retries "5";\nAcquire::http::Timeout "20";\nAcquire::https::Timeout "20";\n' \
      > /etc/apt/apt.conf.d/80-retries; \
    if [ -n "${APT_MIRROR}" ]; then \
      if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then \
        sed -i "s|http://ports.ubuntu.com/ubuntu-ports|${APT_MIRROR}|g; s|http://archive.ubuntu.com/ubuntu|${APT_MIRROR}|g" \
          /etc/apt/sources.list.d/ubuntu.sources; \
      fi; \
    fi; \
    apt-get update -y; \
    apt-get install -y --no-install-recommends \
      passwd ca-certificates curl tar gzip git bash; \
    rm -rf /var/lib/apt/lists/*; \
    if ! getent group fx >/dev/null; then \
      /usr/sbin/groupadd --gid "${FX_GID}" fx 2>/dev/null || /usr/sbin/groupadd fx; \
    fi; \
    if ! id fx >/dev/null 2>&1; then \
      /usr/sbin/useradd --uid "${FX_UID}" --gid fx \
        --create-home --home-dir /home/fx \
        --shell /bin/bash \
        --comment "fx sandbox user" fx \
      2>/dev/null || /usr/sbin/useradd --gid fx \
        --create-home --home-dir /home/fx \
        --shell /bin/bash \
        --comment "fx sandbox user" fx; \
    fi; \
    mkdir -p /workspace /home/fx/.fx /home/fx/.config; \
    chown -R fx:fx /home/fx /workspace; \
    chmod 0700 /home/fx /home/fx/.fx

# fx is a Linux binary inside the image (linux-x86_64 / linux-aarch64).
RUN set -eu; \
    case "${TARGETARCH:-}" in \
      amd64) arch=x86_64 ;; \
      arm64) arch=aarch64 ;; \
      "") case "$(uname -m)" in x86_64|amd64) arch=x86_64 ;; arm64|aarch64) arch=aarch64 ;; *) echo "arch? $(uname -m)"; exit 1 ;; esac ;; \
      *) echo "unsupported TARGETARCH=${TARGETARCH}"; exit 1 ;; \
    esac; \
    ver="${FX_VERSION}"; \
    if [ -z "$ver" ]; then ver="$(curl -fsSL https://releases.fx.sh/latest.txt | tr -d "[:space:]")"; fi; \
    cd /tmp; \
    curl -fsSL -o fx.tgz "https://releases.fx.sh/${ver}/fx-linux-${arch}.tar.gz"; \
    curl -fsSL -o fx.sha "https://releases.fx.sh/${ver}/fx-linux-${arch}.tar.gz.sha256"; \
    got="$(sha256sum fx.tgz | awk "{print \$1}")"; \
    expect="$(awk "{print \$1}" fx.sha | tr -d "[:space:]")"; \
    [ "$got" = "$expect" ] || { echo "sha256 mismatch $got != $expect"; exit 1; }; \
    tar --no-same-owner -xzf fx.tgz; \
    install -m 0755 /tmp/fx /usr/local/bin/fx; \
    rm -rf /tmp/fx /tmp/fx.tgz /tmp/fx.sha; \
    fx --version

COPY entrypoint.sh /usr/local/bin/fx-entrypoint
COPY config/settings.json /usr/local/share/fx-sandbox/settings.json
COPY config/workspace.fx.json /usr/local/share/fx-sandbox/workspace.fx.json

RUN chmod 0755 /usr/local/bin/fx-entrypoint \
 && install -m 0600 -o fx -g fx /usr/local/share/fx-sandbox/settings.json /home/fx/.fx/settings.json \
 && printf "export FX_DISABLE_KEYCHAIN=1\\nexport FX_MODEL=%s\\n" "${FX_MODEL}" > /etc/profile.d/fx.sh \
 && chmod 0644 /etc/profile.d/fx.sh

USER fx:fx
WORKDIR /workspace
STOPSIGNAL SIGINT
ENTRYPOINT ["/usr/local/bin/fx-entrypoint"]
CMD ["fx"]
